name: バグレポート

# 概要
about:
  description: バグの概要
  type: input
  required: true

# 再現手順
reproduction:
  description: バグの再現手順
  type: textarea
  required: true

# 期待される動作
expected:
  description: 期待される動作
  type: input
  required: true

# 実際の動作
actual:
  description: 実際の動作
  type: input
  required: true

# 環境
environment:
  game_version:
    description: ゲームのバージョン
    type: input
    required: true
  platform:
    description: プラットフォーム
    type: input
    required: true
  other_info:
    description: その他の情報
    type: input

# その他
others:
  additional_info:
    description: 修正に向けての提案などがあれば、自由に記述してください。
    type: textarea
